services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "9999:4567"
    depends_on:
      - redis

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"

  redis:
    image: "redis:alpine"
